// client/src/app/features/screener/screener.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ScreenerService } from '../../core/services/screener.service';
import { ScreenerPick } from '../../core/models/stock.model';

@Component({
  selector: 'app-screener',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './screener.component.html',
  styleUrl: './screener.component.scss'
})
export class ScreenerComponent implements OnInit {
  private svc = inject(ScreenerService);

  picks       = signal<ScreenerPick[]>([]);
  status      = signal<'loading' | 'ready' | 'refreshing' | 'error'>('loading');
  updatedAt   = signal('');
  sortKey     = signal<keyof ScreenerPick>('decline_pct');
  sortDir     = signal<1 | -1>(-1);
  filterSec   = signal('all');
  private pollTimer?: ReturnType<typeof setTimeout>;

  ngOnInit() { this.load(true); }

  load(force = false) {
    this.svc.getValuePicks().subscribe(r => {
      if (!r) { this.status.set('error'); return; }
      if (r.status === 'loading') {
        this.status.set('loading');
        this.pollTimer = setTimeout(() => this.load(), 6000);
        return;
      }
      this.picks.set(r.data || []);
      this.status.set(r.status as any);
      if (r.fetched_at) {
        const mins = Math.round((Date.now() / 1000 - r.fetched_at) / 60);
        this.updatedAt.set(mins < 2 ? 'Just updated' : `${mins}m ago`);
      }
      if (r.status === 'refreshing') this.pollTimer = setTimeout(() => this.load(), 10000);
    });
  }

  refresh() {
    this.status.set('loading');
    this.svc.refresh().subscribe(() => {
      this.pollTimer = setTimeout(() => this.load(), 6000);
    });
  }

  sort(key: keyof ScreenerPick) {
    if (this.sortKey() === key) this.sortDir.update(d => d === 1 ? -1 : 1);
    else { this.sortKey.set(key); this.sortDir.set(-1); }
  }

  get sectors(): string[] {
    const s = new Set(this.picks().map(p => p.sector));
    return ['all', ...s];
  }

  get filtered(): ScreenerPick[] {
    let list = this.picks();
    if (this.filterSec() !== 'all') list = list.filter(p => p.sector === this.filterSec());
    const key = this.sortKey(); const dir = this.sortDir();
    return [...list].sort((a, b) => {
      const av = (a as any)[key] ?? 0, bv = (b as any)[key] ?? 0;
      return (av < bv ? -1 : av > bv ? 1 : 0) * dir;
    });
  }

  fmt(n: number | null | undefined, dec = 1): string {
    if (n == null) return '—';
    return n.toLocaleString('en-IN', { maximumFractionDigits: dec });
  }
  fmtCr(n: number | null | undefined): string {
    if (n == null) return '—';
    if (n >= 1e5) return (n / 1e5).toFixed(1) + 'L Cr';
    if (n >= 1e3) return (n / 1e3).toFixed(1) + 'K Cr';
    return n.toFixed(1) + ' Cr';
  }

  ngOnDestroy() { clearTimeout(this.pollTimer); }
}

<div class="screener-wrap">
  <div class="scr-head">
    <div>
      <div class="scr-title">💎 Value Picks</div>
      <div class="scr-sub">
        @if (updatedAt()) { Updated {{updatedAt()}} · }
        {{picks().length}} stocks
      </div>
    </div>
    <button class="scr-refresh" (click)="refresh()" [disabled]="status() === 'loading'">
      ↻ Refresh
    </button>
  </div>

  <!-- Sector filter -->
  @if (picks().length) {
    <div class="scr-filters">
      @for (s of sectors; track s) {
        <button class="scr-chip" [class.active]="filterSec() === s" (click)="filterSec.set(s)">{{s}}</button>
      }
    </div>
  }

  @if (status() === 'loading' && picks().length === 0) {
    <div class="scr-loading">
      <div class="spin"></div>
      <span>Scanning 100+ stocks for value opportunities…</span>
    </div>
  } @else if (status() === 'error') {
    <div class="scr-error">Failed to load screener data. <button (click)="refresh()">Retry</button></div>
  } @else if (filtered.length === 0) {
    <div class="scr-empty">No stocks match the current filter</div>
  } @else {
    <div class="scr-table-wrap">
      <table class="scr-table">
        <thead>
          <tr>
            <th (click)="sort('symbol')">Symbol</th>
            <th (click)="sort('name')">Company</th>
            <th (click)="sort('price')">Price</th>
            <th (click)="sort('pe_ratio')">P/E</th>
            <th (click)="sort('decline_pct')">
              <span [class.sorted]="sortKey()==='decline_pct'">↓ from 52W High</span>
            </th>
            <th (click)="sort('gross_margin')">Gross Margin</th>
            <th (click)="sort('mkt_cap_cr')">Mkt Cap</th>
            <th (click)="sort('beta')">Beta</th>
          </tr>
        </thead>
        <tbody>
          @for (p of filtered; track p.symbol) {
            <tr>
              <td><span class="scr-sym">{{p.symbol.replace('.NS','').replace('.BO','')}}</span></td>
              <td>
                <div class="scr-name">{{p.name}}</div>
                <div class="scr-sec">{{p.sector}}</div>
              </td>
              <td class="num">₹{{fmt(p.price)}}</td>
              <td class="num">{{fmt(p.pe_ratio)}}</td>
              <td class="num dn">-{{fmt(p.decline_pct)}}%</td>
              <td class="num">{{fmt(p.gross_margin)}}%</td>
              <td class="num">{{fmtCr(p.mkt_cap_cr)}}</td>
              <td class="num" [class.up]="p.beta < 1" [class.dn]="p.beta > 1.5">{{fmt(p.beta, 2)}}</td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
</div>

// client/src/components/Screener/Screener.jsx
import React, { useEffect, useState } from 'react';
import { useScreener } from '../../hooks/useScreener';
import { useWatchlist } from '../../hooks/useWatchlist';
import { useAppContext } from '../../contexts/AppContext';
import './Screener.scss';

function fmt(n, dec = 2) { if (n == null) return '—'; return typeof n === 'number' ? n.toFixed(dec) : n; }
function fmtCr(n) {
  if (!n) return '—';
  const cr = n / 1e7;
  if (cr >= 1e5) return `₹${(cr / 1e5).toFixed(1)}L Cr`;
  if (cr >= 1e3) return `₹${(cr / 1e3).toFixed(1)}K Cr`;
  return `₹${cr.toFixed(0)} Cr`;
}

const SORT_OPTS = [
  { label: 'Decline %', value: 'decline_pct' },
  { label: 'P/E', value: 'pe_ratio' },
  { label: 'Gross Margin', value: 'gross_margin' },
  { label: 'Market Cap', value: 'mkt_cap_cr' },
];

export default function Screener() {
  const { stocks, loading, error, load, refresh } = useScreener();
  const { add } = useWatchlist();
  const { dispatch } = useAppContext();
  const [sector, setSector] = useState('All');
  const [sortBy, setSortBy] = useState('decline_pct');
  const [sortDir, setSortDir] = useState('desc');

  useEffect(() => { load(); }, []);

  const sectors = ['All', ...new Set(stocks.map(s => s.sector).filter(Boolean))].sort();

  const filtered = stocks
    .filter(s => sector === 'All' || s.sector === sector)
    .sort((a, b) => {
      const av = a[sortBy] || 0;
      const bv = b[sortBy] || 0;
      return sortDir === 'desc' ? bv - av : av - bv;
    });

  const toggleSort = (field) => {
    if (sortBy === field) setSortDir(d => d === 'desc' ? 'asc' : 'desc');
    else { setSortBy(field); setSortDir('desc'); }
  };

  const pickStock = async (stock) => {
    await add(stock.symbol, stock.name, stock.exchange || 'NSE');
    dispatch({ type: 'SET_CURRENT_SYMBOL', payload: stock.symbol });
    dispatch({ type: 'SET_VIEW', payload: 'stock' });
  };

  return (
    <div className="screener">
      <div className="screener__header">
        <div>
          <h2 className="screener__title">Value Picks</h2>
          <p className="screener__sub">Large-cap NSE stocks ≥10% below 52W high with positive EPS</p>
        </div>
        <button className="screener__refresh" onClick={refresh} disabled={loading}>
          {loading ? <span className="spinner" /> : '↻ Refresh'}
        </button>
      </div>

      <div className="screener__controls">
        <div className="screener__sectors">
          {sectors.map(s => (
            <button
              key={s}
              className={`filter-btn ${sector === s ? 'filter-btn--active' : ''}`}
              onClick={() => setSector(s)}
            >
              {s}
            </button>
          ))}
        </div>

        <div className="screener__sort">
          <span style={{ color: 'var(--text2)', fontSize: 12 }}>Sort by:</span>
          {SORT_OPTS.map(o => (
            <button
              key={o.value}
              className={`filter-btn ${sortBy === o.value ? 'filter-btn--active' : ''}`}
              onClick={() => toggleSort(o.value)}
            >
              {o.label} {sortBy === o.value ? (sortDir === 'desc' ? '↓' : '↑') : ''}
            </button>
          ))}
        </div>
      </div>

      {error && <div className="screener__error">{error}</div>}

      {loading && stocks.length === 0 ? (
        <div className="screener__loading">
          <span className="spinner" />
          <p>Scanning stocks for value opportunities…</p>
        </div>
      ) : filtered.length === 0 ? (
        <div className="screener__empty">No stocks match filters</div>
      ) : (
        <div className="screener__grid">
          {filtered.map(stock => (
            <div key={stock.symbol} className="stock-card" onClick={() => pickStock(stock)}>
              <div className="stock-card__header">
                <div>
                  <div className="stock-card__symbol">{stock.symbol.replace('.NS', '').replace('.BO', '')}</div>
                  <div className="stock-card__name">{stock.name}</div>
                </div>
                <div className="badge badge--down" title="Below 52W High">
                  -{fmt(stock.decline_pct)}%
                </div>
              </div>

              <div className="stock-card__price">
                <span>₹{fmt(stock.price)}</span>
                {stock.sector && <span className="badge badge--accent">{stock.sector}</span>}
              </div>

              <div className="stock-card__stats">
                <div className="kv">
                  <span>P/E</span>
                  <strong className={stock.pe_ratio < 15 ? 'up' : stock.pe_ratio > 40 ? 'down' : ''}>
                    {fmt(stock.pe_ratio)}
                  </strong>
                </div>
                <div className="kv">
                  <span>Gross Margin</span>
                  <strong className={stock.gross_margin > 40 ? 'up' : ''}>
                    {stock.gross_margin ? fmt(stock.gross_margin) + '%' : '—'}
                  </strong>
                </div>
                <div className="kv">
                  <span>Mkt Cap</span>
                  <strong>{fmtCr(stock.mkt_cap_cr * 1e7)}</strong>
                </div>
                <div className="kv">
                  <span>52W High</span>
                  <strong>₹{fmt(stock.week52_high)}</strong>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
